# Generated by Django 4.1.7 on 2023-04-03 16:25

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import users.validate


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z\\s]+$', message='Поле может содержать только буквы')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[а-яА-Яa-zA-Z\\s]+$', message='Поле может содержать только буквы')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validate.validate_username]),
        ),
    ]
